### ISSUE TITLE
Cannot connect to Aria2 docker instance

### ISSUE THREAD

**Issue by scapix** [deblockt/hass-aria2#11]
When setting up integration unknown error occurs.
HA and Aria running in separate dockers.
AriaNG docker connects without problem to Aria2

Logger: custom_components.aria2.config_flow
Source: custom_components/aria2/aria2_client.py:127
Integration: aria2 ([documentation](https://github.com/deblockt/hass-aria2), [issues](https://github.com/deblockt/hass-aria2/issues))
First occurred: 16:40:41 (1 occurrences)
Last logged: 16:40:41

unknow error
Traceback (most recent call last):
  File "/config/custom_components/aria2/config_flow.py", line 39, in async_step_user
    await ws_client.call(GetGlobalOption())
  File "/config/custom_components/aria2/aria2_client.py", line 33, in call
    ws = await self.ws.get()
  File "/config/custom_components/aria2/aria2_client.py", line 127, in get
    self.ws = await websockets.connect(self.url)
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/client.py", line 659, in __await_impl_timeout__
    return await asyncio.wait_for(self.__await_impl__(), self.open_timeout)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 445, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.10/site-packages/websockets/legacy/client.py", line 663, in __await_impl__
    _transport, _protocol = await self._create_connection()
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1064, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1049, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 960, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.1.10', 6800)

**Comment by deblockt** [comment]
Hi, 

It seem that HA can not access to the IP `192.168.1.10` on port `6800`.
Is the port `6800` open on your Aria2  docker configuration? 

Can you access to your aria server using the android/iphone aria app ?

**Comment by scapix** [comment]
Hi,
yes, i'm connecting to that Aria2 instance from another docker image (AriaNG) and just now tested some iOS app.

![IMG_7998](https://user-images.githubusercontent.com/2369415/222953301-6346552e-f81e-4ef5-ab77-d517f3479073.PNG)

**Comment by dur00s** [comment]
I am facing the same issue, have you been able to resolve the issue?

**Comment by kradNZ** [comment]
Also facing similar issue, I think.

**Comment by deblockt** [comment]
Hi, can you share tour aria and home-assistant docker configuration ? I will try to reproduce the issue. 
Are aria and home-assistant on the same server?

**Comment by ChrisLaird** [comment]
> Hi, can you share tour aria and home-assistant docker configuration ? I will try to reproduce the issue. Are aria and home-assistant on the same server?

```version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:rw
    restart: unless-stopped
    privileged: true
    network_mode: host
volumes:
    config:
```
And

```
version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=<SNIP>
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Pacific/Auckland
    volumes:
      - ${PWD}/aria2-config:/config
      - /srv/dev-disk-by-label-Data/Data/aria2download:/downloads
    network_mode: host
    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: 5m

  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 5m
```

**Comment by deblockt** [comment]
Thanks, i will try to reproduce next week

**Comment by deblockt** [comment]
Hi @ChrisLaird I have test your docker and It's working on my size. 
I juste updated one thing on my side because on Mac `network_mode: host` don't work.
So with this files:
```
version: "3.8"

services:

  Aria2-Pro:
    container_name: aria2-pro
    image: p3terx/aria2-pro
    environment:
      - PUID=65534
      - PGID=65534
      - UMASK_SET=022
      - RPC_SECRET=<SNIP>
      - RPC_PORT=6800
      - LISTEN_PORT=6888
      - DISK_CACHE=64M
      - IPV6_MODE=false
      - UPDATE_TRACKERS=true
      - CUSTOM_TRACKER_URL=
      - TZ=Pacific/Auckland
    volumes:
      - ${PWD}/aria2-config:/config
      - ${PWD}/aria2-download:/downloads
    ports:
      - 6800:6800
    restart: unless-stopped

    logging:
      driver: json-file
      options:
        max-size: 5m

  AriaNg:
    container_name: ariang
    image: p3terx/ariang
    command: --port 6880 --ipv6
    restart: unless-stopped
    ports:
      - 6880:6880
    logging:
      driver: json-file
      options:
        max-size: 5m
```
and 
```
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${PWD}/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:rw
    restart: unless-stopped
    privileged: true
    ports:
      - 8123:8123
volumes:
    config:
```

it's working fine. 

To connect home assistant to my aria config, I use the following config: 
- host: `<ip of my mac>` don't use localhost because my docker are not on the same network
- port: default
- secret: `<SNIP>`
- ssl: no
